### PR TITLE
update embedded WG repos

### PR DESCRIPTION
**Pull request by japaric**
Now that most of our teams have OK-ed the use of highfive let's add more repos

### CODE REVIEW

**Comment by pietroalbini** [comment]
Thanks! You need to run the script to update the webhooks now. Redeploying...

**Comment by japaric** [comment]
@pietroalbini thanks! I ran the script locally (and saw all the repos get "added") but highfive is not working (rust-embedded/cortex-m-rt#175). Should I wait a bit more?

**Comment by pietroalbini** [comment]
Did you give highfive write access to all those repos?

**Comment by japaric** [comment]
I forgot! It's working after fixing the perms. Thanks again.

**Pull request merged**
