### PR TITLE
temporarily remove japaric from most highfive rotations

### PR DESCRIPTION
**Pull request by japaric**
I won't have bandwidth for reviews for the next few months due to my thesis work but I'll eventually get back to it.

### CODE REVIEW

**Comment by pietroalbini** [comment]
That was to get your approval :stuck_out_tongue: 
Happy to merge this if it's OK for you.

**Comment by japaric** [comment]
(@pietroalbini note that this is an older, different PR from #198)

**Comment by pietroalbini** [comment]
Oh. Woops...

**Pull request merged**
