### PR TITLE
Use proper markdown list syntax on README.md

### PR DESCRIPTION
**Pull request by ThatNerdyPikachu**

### CODE REVIEW

**Comment by ThatNerdyPikachu** [comment]
(Proper probably isn't the best word for this...
Less of a hassle to add list items?)

**Comment by pietroalbini** [comment]
Thanks!

**Comment by pietroalbini** [comment]
And calm down @rust-highfive, you can't assign issues to yourself.

**Comment by ThatNerdyPikachu** [comment]
Heh

Why is it doing that?

**Comment by pietroalbini** [comment]
Dunno.

**Pull request merged**
