### PR TITLE
link cargo to its CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by dwijnand**
note this is just from a quick look at the code and the README - I'm not sure if this is right, so feedback very welcome.

### CODE REVIEW

**Comment by nrc** [comment]
Heh, I have literally no idea whether this will work! This is a feature from Servo highfive that we don't use. However, it looks like it should work, so let's give it a go!

**Comment by dwijnand** [comment]
assuming this change is what is running, it looks like it didn't work :(

https://github.com/rust-lang/cargo/pull/5367#issuecomment-381754627

**Comment by davidalber** [comment]
I suspect your change has not been deployed. This is what happens on master:
```
>>> from highfive import newpr
>>> config = """{
...     "groups": {
...         "all": ["@alexcrichton", "@matklad"]
...     },
...     "dirs": {
...         "doc": ["doc"]
...     },
...     "contributing": "https://github.com/rust-lang/cargo/blob/master/CONTRIBUTING.md"
... }"""
>>> import json
>>> newpr.welcome_msg('foouser', json.loads(config))
u"Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @foouser (or someone else) soon.\n\nIf any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.\n\nPlease see [the contribution instructions](https://github.com/rust-lang/cargo/blob/master/CONTRIBUTING.md) for more information.\n"
```

**Comment by nrc** [comment]
I deployed just now (I tend to batch changes and deploy once per week or so), so the next PR to Cargo should see this change

**Comment by dwijnand** [comment]
confirmed! 🎉 https://github.com/rust-lang/cargo/pull/5402#issuecomment-383361959

**Pull request merged**
