### PR TITLE
Fixing test by getting `to_mention` in scope for all usages

### PR DESCRIPTION
**Pull request by davidalber**
Unit tests currently fail.
```
$ nosetests
.E.
======================================================================
ERROR: highfive.tests.test_newpr.TestNewPR.test_choose_reviewer
----------------------------------------------------------------------
_StringException: Traceback (most recent call last):
  File "/Users/davidalber/dev/highfive/highfive/tests/test_newpr.py", line 22, in test_choose_reviewer
    fake_config)
  File "/Users/davidalber/dev/highfive/highfive/newpr.py", line 292, in choose_reviewer
    for mention in to_mention:
UnboundLocalError: local variable 'to_mention' referenced before assignment


----------------------------------------------------------------------
Ran 3 tests in 0.139s

FAILED (errors=1)
```

This PR fixes the broken test.

I also recommend someone enable Travis CI on this repository at https://travis-ci.org/rust-lang-nursery/highfive.

### CODE REVIEW

**Comment by davidalber** [comment]
I suspect this also fixes rust-lang/rust-www#1030.

The exception above is raised in current master when `if dirs` is falsy [here](https://github.com/rust-lang-nursery/highfive/blob/43d5603148316a81dfaebd0e07f56daad32810a8/highfive/newpr.py#L221). Variable `dirs` is falsy when it is an empty dict (`{}`), which is it for several repositories, including rust-www (see its [config](https://github.com/rust-lang-nursery/highfive/blob/43d5603148316a81dfaebd0e07f56daad32810a8/highfive/configs/rust-www.json)).

This will result in more PR assignments to the global core members (shown [here](https://github.com/rust-lang-nursery/highfive/blob/master/highfive/configs/_global.json)).

**Comment by davidalber** [comment]
I guess we'd know if that is what's really happening by examining the highfive service logs on @nrc's private server.

**Comment by nrc** [comment]
> I also recommend someone enable Travis CI on this repository

Done!

**Comment by nrc** [comment]
Thank you!

**Pull request merged**
