### PR TITLE
Add machine provisioning and deployment code

### PR DESCRIPTION
**Pull request by davidalber**
# About
This PR adds code to provision an EC2 instance for Highfive and a script to deploy Highfive to that instance. Maybe it's a demonstration or maybe we want to consider using this to really deploy Highfive.

- It aims to mimic (what I know about) the setup that @nrc has for running Highfive right now on his machine (e.g., I've stuck to using Apache to handle executing the CGI script).
- The deployment only works on code living in the remote (i.e., GitHub), so you won't be able to deploy local changes.
- Another consequence of the previous point is that the provisioning code in this PR will not work until the PR lands on master because it expects to be able to find the contents of the PR. I've tested it by using a different repository.
- Credentials (i.e., the GitHub access token) and configuration are encrypted and in the config.secure file. They are encrypted using KMS, an AWS service. Running the deploy script decrypts the file. The file in this PR is the file for me to run Highfive with my own access token. It does not contain the Highfive user's credential, so it won't work for an actual production deployment without additional changes.
- If the directions in the README are followed, provisioning creates a t2.micro instance named "highfive".
- Deployment currently does not blow away old deployment artifacts. New deployments are put into production by symlinking to the deployment directories. The idea here was to allow us to be able to identify versions to roll back to, if necessary.
- Check out the rendered README [here](https://github.com/davidalber/highfive/tree/provision_and_deploy/deployment).

# Alternatives Considered
I started out making a Dockerfile for Highfive and investigating options like Docker Machine and ECS. We could also deploy to a Kubernetes cluster somewhere. We'd also possibly need to use Docker Compose, depending on other choices. The simplest thing would have been to use Docker compose and use that to deploy on an EC2 instance that is set up correctly. Given what we're trying to deploy, I feel the approach taken is simpler, so I went with that. I'm open to feedback.

### CODE REVIEW

**Comment by pietroalbini** [comment]
Currently highfive is (manually) deployed on the `rust-bots` infra machine, along with craterbot. I think @aidanhs wanted to use docker containers to deploy bots though.

**Comment by aidanhs** [comment]
Hi @davidalber, thanks for the PR! I'm particularly excited to get a chance to sit down and read through the KMS stuff, as that may inform how we (infra) 'do' secrets on EC2.

What do you think about using a single Docker container? We can just have a daily cronjob that downloads the latest container, kills the old one and starts the new one (this is in fact how play.rust-lang.org works). Although 'vm-like' containers are generally frowned upon, it does perhaps make this kind of thing simpler.

I'd be particularly interested to hear your thoughts on KMS + Docker.

I'll probably be a little slow at responding over the next two weeks as I'm finishing off some other work, but I hope to check in quickly occasionally to make sure I stay abreast of this.

**Comment by davidalber** [comment]
> What do you think about using a single Docker container? We can just have a daily cronjob that downloads the latest container, kills the old one and starts the new one

If you mean a Docker container that runs Highfive, I think that's fine. Highfive is fronted by Apache, but it's a CGI application (at least right now), not an upstream service, so it all naturally fits into a container.

> I'd be particularly interested to hear your thoughts on KMS + Docker.

As for KMS + Docker, I think it depends on various factors. Incidentally, to set the context: I'm not necessarily an expert on getting secrets into a container, although I've read up on options more than once.

_Orchestration._ I gather you are just planning to `docker run` it on an instance somewhere, but if you have some other orchestration system like Kubernetes or Swarm in mind, I believe they have support for secrets built in. It would probably be worth using those.

Assuming you are not using an orchestration system that can manage secrets, _how many containers is your team going to be managing?_ It was convenient for me to use KMS and put the encrypted blob into the repo, but if you are managing several containers, you might want to separate the secrets management from the code management. That way you don't have to go to different places to change credentials for each container. Also, if you have any containers that use the same credentials, you can manage it in one place.

Putting that aside, though, let's assume you like the in-repo encrypted blob. I'll save writing about other ways to get the secrets into the containers for another comment, if necessary. In the in-repo case, we can have the Docker `CMD` statement execute a script in the repo that first decrypts the secrets in the container (possible since the container will inherit the role of the host EC2 instance) and then run Apache in the foreground.

That strikes me as a fine way to use the encrypted secrets from the repository in the container. I'd want to prototype this to make sure there isn't some fundamental showstopper with what I described. I may do that, but I wanted to get some response to you first.

A potential downside of this is that the resulting image will not be useful to anyone but you (although the approach in the PR has the same limitation), but if you aren't publishing these to Docker Hub as part of CI, that's probably not a problem.

**Comment by davidalber** [comment]
I'm going to go ahead and close this now since I don't see this route being taken. Also, #175 is sort of related and has merged.

**Pull request closed without merging**
